%PDF-1.3
%“Œ‹ž ReportLab Generated PDF document http://www.reportlab.com
1 0 obj
<<
/F1 2 0 R
>>
endobj
2 0 obj
<<
/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font
>>
endobj
3 0 obj
<<
/Contents 7 0 R /MediaBox [ 0 0 612 792 ] /Parent 6 0 R /Resources <<
/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
>> /Rotate 0 /Trans <<

>> 
  /Type /Page
>>
endobj
4 0 obj
<<
/PageMode /UseNone /Pages 6 0 R /Type /Catalog
>>
endobj
5 0 obj
<<
/Author (anonymous) /CreationDate (D:20230217142534-08'00') /Creator (ReportLab PDF Library - www.reportlab.com) /Keywords () /ModDate (D:20230217142534-08'00') /Producer (ReportLab PDF Library - www.reportlab.com) 
  /Subject (unspecified) /Title (untitled) /Trapped /False
>>
endobj
6 0 obj
<<
/Count 1 /Kids [ 3 0 R ] /Type /Pages
>>
endobj
7 0 obj
<<
/Filter [ /ASCII85Decode /FlateDecode ] /Length 370
>>
stream
Gas1Y>t`'h'RelB303@BD!L:N`!=\@C_%]jT<n67c*erV\QRV#2sj):THb_5PMGaUOMiIA1Tu@BM;*`780LW^flRG/_Q01p>b&Qd,f)T\=lW+hh@gt"Asf+YQ#?(W^9PZkf`$W?!dVM7gd9lq6$])n-soM*XAlu5Be7>A/rZT/5I/e9fH3u1$]8*K'c!sh_/h$GY_OGFC-lVT\0@_?H3[5g1dl6Jnq,FQYr3WUORUoED!`,Eq:t4h[5DVJSQFV\.Wlm/Yc]j)oFqO^TDgL,btimS$%$H3S_mJY@Lt$>_)euaPn+q#l(;2GG1pcZC@7AC"d*lR\ZHf^N^G7hM+G[\J,3j"Bj9M8<7-%'4cNBJndV?pXr@~>endstream
endobj
xref
0 8
0000000000 65535 f 
0000000073 00000 n 
0000000104 00000 n 
0000000211 00000 n 
0000000404 00000 n 
0000000472 00000 n 
0000000768 00000 n 
0000000827 00000 n 
trailer
<<
/ID 
[<92a2b4356b95d05d1829d9d786e8bb36><92a2b4356b95d05d1829d9d786e8bb36>]
% ReportLab generated PDF document -- digest (http://www.reportlab.com)

/Info 5 0 R
/Root 4 0 R
/Size 8
>>
startxref
1287
%%EOF
